on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  pull_build_run:
    name: pull-build-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Checking the runner
      run: |
        pwd
        cat /home/runner/work/keka-tracker/keka-tracker/.gitignore
    - name: Deploying to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ${{ secrets.PROJECT_PATH}}
          git pull
          rm .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "PARTIAL_URL=${{ secrets.PARTIAL_URL }}" >> .env
          echo "AVERAGE_URL=${{ secrets.AVERAGE_URL }}" >> .env
          echo "SUMMARY_URL=${{ secrets.SUMMARY_URL }}" >> .env
          sudo docker kill keka-tracker
          sudo docker rm keka-tracker
          sudo docker rmi keka-tracker
          sudo docker build -t keka-tracker .
          sudo docker run -itd -p ${{ secrets.PORT }}:${{ secrets.PORT }} --name keka-tracker keka-tracker
          exit
