on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  pull_build_run:
    name: pull-build-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Creating an env file
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "PARTIAL_URL=${{ secrets.PARTIAL_URL }}" >> .env
        echo "AVERAGE_URL=${{ secrets.AVERAGE_URL }}" >> .env
        echo "SUMMARY_URL=${{ secrets.SUMMARY_URL }}" >> .env
        cat /home/runner/work/keka-tracker/keka-tracker/.env
    - name: Creating the Docker Image
      run: |
        sudo docker build -t keka-tracker .
        sudo docker save -o keka-tracker.tar keka-tracker
        ls -a
    - name: Exporting the Docker Image
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "keka-tracker.tar"
        destination: "${{secrets.PROJECT_PATH}}"
    - name: Deploying to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ${{ secrets.PROJECT_PATH}}
          ls -a
          sudo docker kill keka-tracker
          sudo docker rm keka-tracker
          sudo docker rmi keka-tracker
          sudo docker build -t keka-tracker .
          sudo docker run -itd -p ${{ secrets.PORT }}:${{ secrets.PORT }} --name keka-tracker keka-tracker
          exit
